import { Router } from 'express';
import { makeInvoker } from 'awilix-express';
import AuthController from '../controllers/auth.controller.js';
import { authenticate } from '../middlewares/middleware.js';
const api = makeInvoker(AuthController);
const router = Router();
router.post('/login', api('login'));
router.post('/logout', authenticate, api('logout'));
router.post('/register', authenticate, api('register'));
router.post('/refresh-token', api('refreshToken'));
router.put('/change-password', authenticate, api('changePassword'));
export default router;
