import { Router } from 'express';
import { makeInvoker } from 'awilix-express';
import NotificationController from '../controllers/notification.controller.js';
import { authenticate } from '../middlewares/middleware.js';
const api = makeInvoker(NotificationController);
const router = Router();
router.get('/', authenticate, api('getMyNotifications'));
router.patch('/:id/read', authenticate, api('markRead'));
router.patch('/read-all', authenticate, api('markAllRead'));
export default router;
