import { Router } from 'express';
import { makeInvoker } from 'awilix-express';
import PaymentController from '../controllers/payment.controller.js';
import { authenticate, authorize } from '../middlewares/middleware.js';
const api = makeInvoker(PaymentController);
const router = Router();
router.get('/', authenticate, authorize(['Manager', 'Receptionist']), api('getAll'));
router.get('/report', authenticate, authorize(['Manager']), api('getRevenueReport'));
router.get('/:id', authenticate, api('getById'));
export default router;
