import { Router } from 'express';
import { makeInvoker } from 'awilix-express';
import UserController from '../controllers/user.controller.js';
import { authenticate, authorize } from '../middlewares/middleware.js';
const api = makeInvoker(UserController);
const router = Router();
router.get('/me', authenticate, api('getProfile'));
router.put('/me', authenticate, api('updateProfile'));
router.get('/', authenticate, authorize(['Manager']), api('getAllUsers'));
router.get('/statistics', authenticate, authorize(['Manager']), api('getStatistics'));
router.patch('/:id/status', authenticate, authorize(['Manager']), api('updateUserStatus'));
router.patch('/:id/role', authenticate, authorize(['Manager']), api('changeUserRole'));
router.delete('/:id', authenticate, authorize(['Manager']), api('softDeleteUser'));
export default router;
